const Courses = [
  {
    id: "1",
    title: "Web Development",
    Image: require("../../assets/Crouse1.jpg"),
    description: "dssdfsdfsdfsdfdsds dsfsdfsdfsff fdssfsfsf",
    course1: "HTML",
    course2: "CSS",
    course3: "Javascript",
    price: 5000,
  },
  {
    id: "2",
    title: "Web Development",
    Image: require("../../assets/home.jpg"),
    description: "dssdfsdfsdfsdfdsds dsfsdfsdfsff fdssfsfsf",
    course1: "HTML",
    course2: "CSS",
    course3: "Javascript",
    price: 5000,
  },
//   {
//     id: "1",
//     title: "Web Development",
//     Image: require("../../assets/home.jpg"),
//     description: "dssdfsdfsdfsdfdsds dsfsdfsdfsff fdssfsfsf",
//     course1: "HTML",
//     course2: "CSS",
//     course3: "Javascript",
//     price: 5000,
//   },
//   {
//     id: "1",
//     title: "Web Development",
//     Image: require("../../assets/home.jpg"),
//     description: "dssdfsdfsdfsdfdsds dsfsdfsdfsff fdssfsfsf",
//     course1: "HTML",
//     course2: "CSS",
//     course3: "Javascript",
//     price: 5000,
//   },
//   {
//     id: "1",
//     title: "Web Development",
//     Image: require("../../assets/home.jpg"),
//     description: "dssdfsdfsdfsdfdsds dsfsdfsdfsff fdssfsfsf",
//     course1: "HTML",
//     course2: "CSS",
//     course3: "Javascript",
//     price: 5000,
//   },
//   {
//     id: "1",
//     title: "Web Development",
//     Image: require("../../assets/home.jpg"),
//     description: "dssdfsdfsdfsdfdsds dsfsdfsdfsff fdssfsfsf",
//     course1: "HTML",
//     course2: "CSS",
//     course3: "Javascript",
//     price: 5000,
//   },
 ];

export default Courses;